"""create anime_cache table

Revision ID: e2c16e92553e
Revises: d9b24f46535b
Create Date: 2026-02-21 14:00:09.369083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2c16e92553e'
down_revision: Union[str, Sequence[str], None] = 'd9b24f46535b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anilist_id', sa.Integer(), nullable=False),
    sa.Column('title_romaji', sa.String(length=255), nullable=False),
    sa.Column('title_english', sa.String(length=255), nullable=True),
    sa.Column('title_native', sa.String(length=255), nullable=True),
    sa.Column('episode_count', sa.Integer(), nullable=True),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('genres', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('demographic', sa.String(length=50), nullable=True),
    sa.Column('cached_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anime_cache_anilist_id'), 'anime_cache', ['anilist_id'], unique=True)
    op.create_index(op.f('ix_anime_cache_id'), 'anime_cache', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anime_cache_id'), table_name='anime_cache')
    op.drop_index(op.f('ix_anime_cache_anilist_id'), table_name='anime_cache')
    op.drop_table('anime_cache')
    # ### end Alembic commands ###
